---
**Task 1.** У тебе є дані по користувачу за два дні:

- **День 1**: вектор `v1 = (перегляди, лайки, коментарі) = (10, 3, 1)`
- **День 2**: `v2 = (7, 5, 0)`

In [ ]:
import numpy as np

v1 = np.array([10, 3, 1])
v2 = np.array([7, 5, 0])

# use operation + in numpy 
# code

ans = v1 + v2
print(ans)

# v1_l, v2_l = [10, 3, 1], [7, 5, 0]

# if len(v1_l) != v2_l:
#     raise ValueError("Not equal size")

# ans = [v1_l[i] + v2_l[i] for i in range(len(v1_l))]
# print(ans)
    



[17  8  1]


ValueError: Not equal size

---
Task 1.1 
Дані
У користувача є активність за 3 дні:

- День 1 → `v1 = (12 переглядів, 3 лайки, 1 коментар)`
- День 2 → `v2 = (20, 5, 0)`
- День 3 → `v3 = (8, 2, 1)`

In [5]:
import numpy as np

v1 = np.array([12, 3, 1])
v2 = np.array([20, 5, 0])
v3 = np.array([8, 2, 1])

ans_1 = v1 + v2 + v3
print(ans_1)

# use operation + in numpy 
# code

[40 10  2]


---
**Task 2.** Є два користувачі зі схожого сегменту:

> u1 = (перегляди, лайки, підписки) = (30, 4, 1) \
> u2 = (20, 6, 0)

Потрібно зрозуміти, чим відрізняється їхня поведінка.

In [6]:
import numpy as np

u1 = np.array([30, 4, 1])
u2 = np.array([20, 6, 0])


ans_2 = u1 - u2
print(ans_2)
# use operation - in numpy
# code

[10 -2  1]


---
**Task 2.2**
Поведінка користувача за 2 тижні:

Тиждень 1 → w1 = (100 переглядів, 15 лайків, 3 підписки)

Тиждень 2 → w2 = (140, 18, 5)

In [7]:
import numpy as np

w1 = np.array([100, 15, 3])
w2 = np.array([140, 18, 5])

print(w1 - w2)

# use operation - in numpy

[-40  -3  -2]


---
**Task 3.1**  З’ясувати, хто “сильніший” за загальною активністю.

Два користувачі: \
u1 = (50 переглядів, 10 лайків, 4 підписки) \
u2 = (70, 5, 1)



In [11]:
import numpy as np

u1 = np.array([50, 10, 4])
u2 = np.array([70, 5, 1])

len_u1 = np.linalg.norm(u1)
len_u2 = np.linalg.norm(u2)


if len_u1 > len_u2:
    print("len_u1 winner")
else:
    print("len_u2 winner")    



# use linalg.norm

len_u2 winner


---
**Task 4.** Двоє користувачів у просторі ознак:

> u1 = (перегляди, лайки) = (10, 2) \
> u2 = (15, 5)

Потрібно:
> знайти відстань між ними (евклідова), \
> зрозуміти, хто “активніший” у загальному масштабі.

In [14]:
# 1. Відстань між користувачами

# use np.linalg.norm
# code 

u_1 = np.array([10, 2])
u_2 = np.array([15, 5])

print("distance:", np.linalg.norm(u_1 - u_2))


# 2. Рівень активності кожного (довжина вектора)
# use np.linalg.norm
# code 

print("u1:", np.linalg.norm(u1))
print("u2:", np.linalg.norm(u2))

distance: 5.830951894845301
u1: 51.146847410177685
u2: 70.18546858146635


---
**Task 5.** Нормалізація поведінкових фіч перед кластеризацією


In [20]:
import numpy as np

users = np.array([
    [10, 3, 1],
    [40, 2, 0],
    [20, 5, 2],
    [15, 1, 1],
    [60, 7, 3]
])

print(np.linalg.norm(users))
users_1 = np.linalg.norm(users)

print(np.linalg.norm(users) / users_1)

norm_ = np.linalg.norm(users, axis = 1, keepdims=True)

normalize_users = users / norm_

print(normalize_users)

# use linalg.norm
# users / by previos step

77.64019577512668
1.0
[[0.95346259 0.28603878 0.09534626]
 [0.99875234 0.04993762 0.        ]
 [0.9656091  0.24140227 0.09656091]
 [0.99558497 0.06637233 0.06637233]
 [0.99204049 0.11573806 0.04960202]]


---
**Task 5.** Оцініть наскільки користувачу підходить товар

In [19]:
# user data 
#u = (0.2, 0.8, 0.3, 0.1)

# product data
#p = (0.25, 0.75, 0.2, 0.15)


import numpy as np

u = np.array([0.2, 0.8, 0.3, 0.1])
m = np.array([0.25, 0.75, 0.2, 0.15])

score = np.dot(u, m) 
print(score)

0.7250000000000002


In [25]:
u = np.array([0.2, 0.8, 0.3, 0.1])
m = np.array([0.25, 0.75, 0.2, 0.15])

def cos_sim(u, m):
    return np.dot(u,m) / (np.linalg.norm(u) * np.linalg.norm(m))

print(cos_sim(u, m))

0.9900436758984326


In [ ]:
# Cosine similarity показує, наскільки два вектори схожі за напрямом, ігноруючи їхній масштаб.
# Косинус кута між ними:
# - 1 — стрілки співпадають → повна схожість
# - 0 — стрілки перпендикулярні → немає зв’язку
# - (-1) — стрілки протилежні → повна несумісність